### ISSUE TITLE
segfault in gl_sprite.cpp with very old hardware

### ISSUE THREAD

**Issue by bmorel** [Bertram25/ValyriaTear#461] opened 2015-05-01 20:48 UTC
As requested, I am reporting an issue aboug a segfault line 96: "glGenVertexArrays(1,arrays);".

IMHO, this segfault is because of my hardware and/or the mesa hardware accelerated implementation on Debian 7 (wheezy, which recently became old-stable. Not sure that I'll go to current stable...).

I determined this, because when using the package libgl1-mesa-swx11, which is a pure software rasteriser, the crash does not happen (but, the game is not usable, even the main menu is damn too slow to be usable. Not really surprising, I'll describe my hardware after that description). Using NVidia (legacy) drivers or nouveau plus libgl1-mesa-dri makes the software crashing.

The hardware in question is:
CPU: AMD Athlon(tm) XP Processor 2800+
RAM: 1.2Gb
GPU: NVIDIA Corporation NV17 [GeForce4 420 Go 32M] (rev a3)

I only used this computer to compile and try VT because it's my last portable computer. I did not really expected it to be able to run VT comfortably, but I really wanted to retry the game with recent improvements :)
Now, some games (low resources consumer) are able to run on that computer, so I still wanted to try (I have 7kaa, wesnoth, flare, geki2 installed. Oh, and pacman hehe). I think the point here is that those games does NOT uses openGL, they all only use SDL 1.6. I guess OpenGL 1 could be used, but only old versions (according to wikipedia, 1.2 or 1.3).

Now... if you really want to play with such hardware, I could help. Could be fun, but I have to admit that it would be a complete, pure, waste of time. Thinking about it, it might be fun to try to work on that. No job atm :p

PS: Btw... github is a real pain with that hardware... I really hate when there is that much JS in websites!

**Comment by lieff** [comment] 2015-05-02 23:56
try this http://stackoverflow.com/questions/8302625/segmentation-fault-at-glgenvertexarrays-1-vao

**Comment by Bertram25** [comment] 2015-05-03 08:49
glewExperimental = GL_TRUE; 
glewInit();

Thanks a lot @lieff :) Could you try this @bmorel ?

**Comment by bmorel** [comment] 2015-05-03 13:56
Just tried it. Now, I have tons of error messages, before the crash. Failure to create shaders. Not surprising, if I am right (I am not an openGL expert... not even a newbie, honestly), because shaders are a feature which appeared in openGL v2. My GPU only seems to support openGL v1.3.

As I said, I doubt it's worth trying to work on this issue.

Here is a sample of the error messages (can't find how to attach the full file): 

==========
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader.cpp:Shader:39: 
Failed to create the shader.
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader.cpp:Shader:39: 
Failed to create the shader.
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader.cpp:Shader:39: 
Failed to create the shader.
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader.cpp:Shader:39: 
Failed to create the shader.
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader.cpp:Shader:39: 
Failed to create the shader.
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:ShaderProgram:60: 
Failed to attach the vertex shader to the shader program. Shader Program ID: 1 Shader ID: 0
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:ShaderProgram:60: 
Failed to attach the vertex shader to the shader program. Shader Program ID: 2 Shader ID: 0
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:ShaderProgram:60: 
Failed to attach the vertex shader to the shader program. Shader Program ID: 3 Shader ID: 0
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:ShaderProgram:60: 
Failed to attach the vertex shader to the shader program. Shader Program ID: 4 Shader ID: 0
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:Load:170: 
Failed to load the shader program. Shader Program ID: 3
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:UpdateUniform:243: 
Failed to update the shader program uniform. Shader Program ID: 3 Uniform Name: u_Model
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:UpdateUniform:243: 
Failed to update the shader program uniform. Shader Program ID: 3 Uniform Name: u_View
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:UpdateUniform:243: 
Failed to update the shader program uniform. Shader Program ID: 3 Uniform Name: u_Projection
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:UpdateUniform:243: 
Failed to update the shader program uniform. Shader Program ID: 3 Uniform Name: u_Color
ERROR:/home/berenger/contrib/ValyriaTear/src/engine/video/gl/gl_shader_program.cpp:Load:170: 
Failed to load the shader program. Shader Program ID: 3
==========

**Comment by Bertram25** [comment] 2015-05-04 11:34
Thanks @bmorel :)

At least we've learned something useful about glew thanks to @lieff ;)
I'll close the issue but the log makes at least clear the issue is about the harware not supporting shaders.

**Closed by Bertram25** 2015-05-04 11:34 UTC

**Comment by bmorel** [comment] 2015-05-05 22:31
Indeed. I had found that message previously, but my instinct said me it would probably not be this small line of code. I only tried that because it was explicitly asked, and because I am a true newbie when things are related to OpenGL.
